const assert = require('node:assert/strict');
const metrics = require('../assets/metrics.js');
const sheets = require('../assets/sheets.js');
const defs = metrics.definitions({});
for (const [value, label] of [[0, 'Unaware'], [0.5, 'Rumors'], [25, 'Noticed'], [75, 'Watching'], [100, 'Closely watching']]) assert.equal(metrics.band(defs[0], value).label, label);
for (const [value, label] of [[-100, 'Hostile'], [-75, 'Hostile'], [-74.5, 'Unfriendly'], [-25, 'Unfriendly'], [0, 'Neutral'], [25, 'Friendly'], [75, 'Allied']]) assert.equal(metrics.band(defs[1], value).label, label);
const influence = {field: 'influence', name: 'Influence', min: 0, max: 10, suffix: ' / 10', bands: [{max: 3, label: 'Limited'}, {max: 10, label: 'Dominant'}]};
const custom = metrics.definitions({metrics: [...defs, influence]});
const data = sheets.convert('id,name,awareness,opinion,influence\na,Alpha,80,-40,5', custom);
metrics.validateValues(data.factions[0], custom);
assert.equal(data.factions[0].influence, 5);
assert.equal(metrics.formatted(influence, 5), '5 / 10');
assert.throws(() => sheets.convert('id,name,awareness,opinion\na,Alpha,80,-40', custom), /influence column/);
assert.throws(() => metrics.validateValues({...data.factions[0], influence: 11}, custom), /between 0 and 10/);
assert.throws(() => metrics.definitions({metrics: [influence, influence]}), /unique field/);
assert.throws(() => metrics.definitions({metrics: [{...influence, baseline: 10}]}), /baseline/);
assert.throws(() => metrics.definitions({metrics: [{...influence, bands: [{max: 3, label: 'Incomplete'}]}]}), /last band/);
assert.throws(() => metrics.definitions({metrics: [{...influence, bands: [{max: 10, label: 'A'}, {max: 3, label: 'B'}]}]}), /ascending/);
assert.throws(() => metrics.definitions({metrics: [{...influence, field: 'name'}]}), /text field/);
assert.equal(metrics.definitions({text: {awareness: 'Attention'}})[0].name, 'Attention');
console.log('Configurable meter boundaries, extra values, validation, and legacy config checks passed.');
