const assert = require('node:assert/strict');
const sheets = require('../assets/sheets.js');
assert.deepEqual(sheets.parseCSV('\uFEFFa,b\r\n"line\nwith ""quotes""",end\r\n'), [['a', 'b'], ['line\nwith "quotes"', 'end']]);
const data = sheets.convert('name,opinion,id,awareness,blurb,updatedAt\nTest,-40,test,80,"First, second\nthird",2026-10-08\n,,,,,\n');
assert.equal(data.factions.length, 1);
assert.equal(data.factions[0].opinion, -40);
assert.equal(data.factions[0].blurb, 'First, second\nthird');
assert.equal(data.updatedAt, '2026-10-08');
assert.throws(() => sheets.convert('id,name,awareness,opinion\na,A,,0'), /plain number/);
assert.throws(() => sheets.convert('id,name,awareness,opinion\na,A,80%,0'), /plain number/);
assert.throws(() => sheets.convert('id,name,awareness,opinion\na,A,0x10,0'), /plain number/);
assert.throws(() => sheets.convert('id,name,awareness,opinion,id'), /exactly one/);
assert.throws(() => sheets.convert('id,name'), /awareness/);
assert.throws(() => sheets.parseCSV('"unfinished'), /Unclosed/);
assert.equal(sheets.convert('id,name,awareness,opinion\n').factions.length, 0);
assert.match(sheets.url({spreadsheetId: 'abc-123', gid: '0'}), /gid=0/);
assert.match(sheets.url({spreadsheetId: 'abc-123', sheet: 'Campaign notes'}), /sheet=Campaign\+notes/);
assert.throws(() => sheets.url({spreadsheetId: '../private'}), /spreadsheetId/);
assert.equal(sheets.convert('id,name,awareness,opinion,censored\na,A,0,0,TRUE').factions[0].censored, true);
assert.equal(sheets.convert('id,name,awareness,opinion,censored\na,A,0,0,false').factions[0].censored, false);
assert.equal(sheets.convert('id,name,awareness,opinion\na,A,0,0').factions[0].censored, false);
assert.throws(() => sheets.convert('id,name,awareness,opinion,censored\na,A,0,0,maybe'), /censored must/);
console.log('Google Sheets parser and configuration checks passed.');
